spring:
  application:
    name: "DevBlog"
    version: "v1"

  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/devblog}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    active: linux

server:
  port: 8080
#  servlet:
#    context-path: /api

jwt:
  signerKey: "VKnmoynIIjQPXuNksYl87mca+UssmhVO3EYoVAnD4op+qp1aaE6SKMWoIvZy/eKd"