spring:
  application:
    name: "DevBlog"
    version: "v1"

  datasource:
    url: "jdbc:mysql://localhost:3306/devblog"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  signerKey: "VKnmoynIIjQPXuNksYl87mca+UssmhVO3EYoVAnD4op+qp1aaE6SKMWoIvZy/eKd"


file:
  upload-dir: C:/Users/Admin/Pictures/devblog_image_upload